name: UPGRADE

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: 
    - master

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
    - name: Install Cloud Foundry CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf-cli

    - name: Login IBM Cloud
      run: |
        cf login -a ${{secrets.API_SERVER}} -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}

    - name: Download Latest Release
      run: |
        wget -q https://github.com/p4gefau1t/trojan-go/releases/download/v0.8.2/trojan-go-linux-amd64.zip
        unzip trojan-go-linux-amd64.zip trojan-go
        rm -rf trojan-go-linux-amd64.zip
        chmod 700 trojan-go
        
    - name: Write configuration
      run: |
        cat > config.json << EOF
        {
          "run_type": "server",
          "local_addr": "0.0.0.0",
          "local_port": 8080,
          "remote_addr": "www.foxzc.com",
          "remote_port": 80,
          "log_level": 3,
          "password": [
            "123456"
          ],
          "transport_plugin": {
            "enabled": true,
            "type": "plaintext"
          },
          "router": {
            "enabled": false
          },
          "websocket": {
            "enabled": true,
            "path": "/foxzc",
            "hostname": "zchfox.us-south.cf.appdomain.cloud"
          }
        }
        EOF

    - name: Write manifest
      run: |
        cat > manifest.yml << EOF
        applications:
        - name: ${{secrets.APPNAME}}
          memory: 256M
          random-route: true
          command: ./trojan-go
          buildpacks:	
          - binary_buildpack
        EOF

    - name: Push
      run: |
        cf push
        
